[project]
name = "Flann"
version = 0.1
description = "Flann's programmable instruments python control"

dependencies = [
    "pyserial >= 3.5"

[project.urls]
homepage = "https://flann.com/"
repository = "https://github.com/leonknight99-flann/FlannController"